server:
  port: 8081
spring:
  application:
    name: barraca_lenia
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
    username: postgres.dokknuylfwcjcuimgvrx
    password: "uMP7Y@rp+S?n5y$"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        order_inserts: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
